### ISSUE TITLE
Annoying error

### ISSUE THREAD

**Issue by dawidof** [luciuschoi/lightbox-bootstrap-rails#7]
Receiving on every page loading error in console

```bash
ActionController::RoutingError (No route matches [GET] "/assets/ekko-lightbox.min.css.map"):

actionpack (5.0.2) lib/action_dispatch/middleware/debug_exceptions.rb:53:in `call'
newrelic_rpm (4.0.0.332) lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call'
web-console (3.4.0) lib/web_console/middleware.rb:135:in `call_app'
web-console (3.4.0) lib/web_console/middleware.rb:28:in `block in call'
web-console (3.4.0) lib/web_console/middleware.rb:18:in `catch'
web-console (3.4.0) lib/web_console/middleware.rb:18:in `call'
newrelic_rpm (4.0.0.332) lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call'
actionpack (5.0.2) lib/action_dispatch/middleware/show_exceptions.rb:31:in `call'
newrelic_rpm (4.0.0.332) lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call'
railties (5.0.2) lib/rails/rack/logger.rb:36:in `call_app'
railties (5.0.2) lib/rails/rack/logger.rb:24:in `block in call'
activesupport (5.0.2) lib/active_support/tagged_logging.rb:69:in `block in tagged'
activesupport (5.0.2) lib/active_support/tagged_logging.rb:26:in `tagged'
activesupport (5.0.2) lib/active_support/tagged_logging.rb:69:in `tagged'
railties (5.0.2) lib/rails/rack/logger.rb:24:in `call'
newrelic_rpm (4.0.0.332) lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call'
sprockets-rails (3.2.0) lib/sprockets/rails/quiet_assets.rb:11:in `block in call'
activesupport (5.0.2) lib/active_support/logger_silence.rb:20:in `silence'
activesupport (5.0.2) lib/active_support/logger.rb:63:in `block (3 levels) in broadcast'
activesupport (5.0.2) lib/active_support/logger_silence.rb:20:in `silence'
activesupport (5.0.2) lib/active_support/logger.rb:61:in `block (2 levels) in broadcast'
sprockets-rails (3.2.0) lib/sprockets/rails/quiet_assets.rb:11:in `call'
newrelic_rpm (4.0.0.332) lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call'
actionpack (5.0.2) lib/action_dispatch/middleware/request_id.rb:24:in `call'
newrelic_rpm (4.0.0.332) lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call'
rack (2.0.1) lib/rack/method_override.rb:22:in `call'
newrelic_rpm (4.0.0.332) lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call'
rack (2.0.1) lib/rack/runtime.rb:22:in `call'
newrelic_rpm (4.0.0.332) lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call'
activesupport (5.0.2) lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
newrelic_rpm (4.0.0.332) lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call'
actionpack (5.0.2) lib/action_dispatch/middleware/executor.rb:12:in `call'
newrelic_rpm (4.0.0.332) lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call'
actionpack (5.0.2) lib/action_dispatch/middleware/static.rb:136:in `call'
newrelic_rpm (4.0.0.332) lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call'
rack (2.0.1) lib/rack/sendfile.rb:111:in `call'
newrelic_rpm (4.0.0.332) lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call'
railties (5.0.2) lib/rails/engine.rb:522:in `call'
newrelic_rpm (4.0.0.332) lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call'
puma (3.8.2) lib/puma/configuration.rb:224:in `call'
puma (3.8.2) lib/puma/server.rb:600:in `handle_request'
puma (3.8.2) lib/puma/server.rb:435:in `process_client'
puma (3.8.2) lib/puma/server.rb:299:in `block in run'
puma (3.8.2) lib/puma/thread_pool.rb:120:in `block in spawn_thread'
```

Please remove map line from file or make sth else

**Comment by Okomikeruko** [comment]
I had to roll back to version 3.3.0.3 because this error message was less annoying: 

```
DEPRECATION WARNING: Extra .css in SCSS file is unnecessary. Rename 
/usr/local/rvm/gems/ruby-2.2.2/gems/lightbox-bootstrap-rails-3.3.0.3/vendor/assets/stylesheets/lightbox-bootstrap.css.scss 
to 
/usr/local/rvm/gems/ruby-2.2.2/gems/lightbox-bootstrap-rails-3.3.0.3/vendor/assets/stylesheets/lightbox-bootstrap.scss. 
(called from _app_views_layouts_application_html_haml__3810064660071991527_69895092101360 at 
/home/ubuntu/workspace/petersenwest/app/views/layouts/application.html.haml:10)
```

**Comment by bmalets** [comment]
Fixed current problem in #8. I will be grateful for the review.
